name: CI
on: [pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress
      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "ls tests:"
          ls -la tests || true
      - name: Run tests with phpunit
        run: php artisan test --coverage-clover=coverage.xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
